apiVersion: v1
kind: Service
metadata:
  name: svc-multitool
spec:
  selector:
    app: multitool
  ports:
    - name: for-nginx
      port: 9001
      targetPort: 80
    - name: for-multitool
      port: 9002
      targetPort: 8080
